# Config file for AttnFPN backbone

# General training
experiment_name: test #anchor_matcher_1fmap_fpn_soft_labels_1match_1giou_fmap404064
device: cuda:7
val_interval: 1
debug_mode: False  # doesn't save checkpoints
seed: 10

epochs: 1200 # prev: 50
lr: 2e-4
lr_backbone: 2e-5
lr_linear_proj_mult: 0.1
weight_decay: 1e-4
clip_max_norm: 0.1

# Scheduler
lr_drop: 1000  # prev: 40

# Data
dataset: transoar_testing_focused_attn_160_160_256_CT
overfit: False # use same set consisting of one image for train and val
bbox_padding: 1

# Dataloader
batch_size: 1
shuffle: True
num_workers: 4

# Matching
anchor_matching: True
set_cost_class: 0 #2
set_cost_bbox: 0 #5
set_cost_giou: 1 #2
set_cost_center: 0

# Losses
loss_coefs:
  cls: 2
  bbox: 5
  giou: 2

# Model specific params
backbone:
  name: attn_fpn
  
  # Encoder
  use_attn: False

  # Standard params
  conv_kernels: [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]  # C0, C1, C2, C3, C4, C5
  strides: [[1, 1, 1], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]]
  in_channels: 1  #  Input channels 
  start_channels: 32  # Channels after first encoder block 
  channel_gain: 2 # Channel gain after each encoder block 
  max_channels: 320

  # Swin transformer params

  # Decoder
  use_attn: False
  
  # Standard params
  fpn_channels: 128 # Final output channels
    



  # FPN
  start_filts: 24
  end_filts: 48
  res_architecture: resnet50
  n_channels: 1
  norm: null
  relu: relu
  n_latent_dims: 0
  operate_stride1: False  # Takes forever to train
  sixth_pooling: False

  # Input proj
  num_fmap: 0

  # Swin
  use_swin: False #True
  pretrained: null
  pretrained_2d: True
  patch_size: [4, 4, 4]
  in_chans: 1
  embed_dim: 96
  depths: [2, 1, 1, 1]
  num_heads: [3, 6, 12, 24]
  window_size: [5, 5, 5]  # [7, 7, 7]
  mlp_ratio: 4
  qkv_bias: True
  qk_scale: null
  drop_rate: 0.
  attn_drop_rate: 0.
  drop_path_rate: 0.2
  patch_norm: False
  frozen_stages: -1
  use_checkpoint: False

neck:
  name: focused_attn
  skip_con: False # from backbone to heads
  pos_encoding: sine

  hidden_dim: 512 #832 # prev: 256
  dropout: 0.1  # prev: 0.1
  nheads: 8 #26 #6  #prev: 8
  dim_feedforward: 1024 # prev: 1024
  dec_layers: 2 #6

  num_queries: 540
  input_shapes: [[40, 40, 64]] #[[20, 20, 32]]
  num_feature_levels: 1
  queries_per_organ: 27 #20
  anchor_offsets: 0.1
  num_organs: 20
  aux_loss: True

# Augmentation
augmentation:
  use_augmentation: True
  patch_size: [160, 160, 256] #null #[64, 64, 64]

  p_gaussian_noise: 0 #0.1
  p_gaussian_smooth: 0 #0.1
  p_intensity_scale: 0.5 #0.2
  p_intensity_shift: 0.5 #0.2
  p_adjust_contrast: 0 #0.2
  p_rotate: 0.5
  p_zoom: 0.5
  p_shear: 0.5
  p_translate: 0.5 # 0
  p_flip: 0 #0.5

  gaussian_noise_mean: 0.0
  gaussian_noise_std: 0.1
  gaussian_smooth_sigma: [0.5, 1.0]

  intensity_scale_factors: 0.1 #[0.75, 1.25]
  intensity_shift_offsets: 0.1

  adjust_contrast_gamma: [0.7, 1.5]

  rotation: [-15, 15]
  min_zoom: 0.8
  max_zoom: 1.2 
  translate_precentage: 10
  shear_range: [0.1, 0.1, 0.1]
  flip_axis: [0, 1, 2]