# Config file for AttnFPN-DETR

# General training
experiment_name: detr_visceral
device: cuda:6
val_interval: 1
debug_mode: False  # Doesn't save checkpoints
seed: 10

epochs: 4000
lr: 2e-4
lr_backbone: 2e-5
weight_decay: 1e-4
clip_max_norm: -1   # Not used

# Scheduler
lr_drop: 2500

# Data
dataset: transoar_testing_focused_attn_160_160_256_CT
overfit: False # Use same set consisting of one image for train and val
bbox_padding: 1

# Dataloader
batch_size: 2
shuffle: True
num_workers: 16

# Hungarian matching
set_cost_class: 1
set_cost_bbox: 5
set_cost_giou: 2

# Losses
loss_coefs:
  cls: 2      # Detection
  bbox: 5
  giou: 2
  segce: 2    # Segmentation proxy
  segdice: 2

# Model specific params
backbone:
  name: attn_fpn
  
  # Encoder
  use_encoder_attn: False # Activates swin encoder

  # Standard params
  conv_kernels: [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]  # C0, C1, C2, C3, C4, C5
  strides: [[1, 1, 1], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]]
  in_channels: 1  #  Input channels 
  start_channels: 24  # Channels after first encoder block

  # Swin transformer params
  depths: [2, 2, 2, 2]
  num_heads: [3, 6, 12, 24]
  window_size: [5, 5, 5]
  mlp_ratio: 4
  qkv_bias: True
  qk_scale: null
  drop_rate: 0.
  attn_drop_rate: 0.
  drop_path_rate: 0.2
  conv_merging: False # Not tested yet

  # Decoder
  use_decoder_attn: False # Activated def attn
  
  # Standard params
  fpn_channels: 384 # Final output channels
  out_fmaps: [P2]  # P0, P1, P2, P3, P4, P5

  # Def attn params
  pos_encoding: sine
  feature_levels: [P3, P4, P5]
  hidden_dim: 384
  dim_feedforward: 1024
  dropout: 0.1
  nheads: 6
  layers: 2 #6
  n_points: 4 #4
  use_cuda: False

  # Segmentation proxy loss
  use_seg_proxy_loss: False
  fg_bg: True

neck:
  name: detr
  input_level: P2
  use_encoder: False
  
  pos_encoding: sine
  hidden_dim: 384
  dropout: 0.0
  nheads: 8
  dim_feedforward: 1024
  enc_layers: 3
  dec_layers: 3
  pre_norm: False
  num_queries: 100
  aux_loss: True

  num_organs: 20

# Augmentation
augmentation:
  use_augmentation: True
  patch_size: [160, 160, 256]

  p_gaussian_noise: 0
  p_gaussian_smooth: 0
  p_intensity_scale: 0.5
  p_intensity_shift: 0.5
  p_adjust_contrast: 0
  p_rotate: 0.5
  p_zoom: 0.5
  p_shear: 0
  p_translate: 0.5
  p_flip: 0

  gaussian_noise_mean: 0.0
  gaussian_noise_std: 0.1
  gaussian_smooth_sigma: [0.5, 1.0]

  intensity_scale_factors: 0.1
  intensity_shift_offsets: 0.1

  adjust_contrast_gamma: [0.7, 1.5]

  rotation: [-15, 15]
  min_zoom: 0.8
  max_zoom: 1.2 
  translate_precentage: 10
  shear_range: [0.1, 0.1, 0.1]
  flip_axis: [0, 1, 2]