# Config file for AttnFPN backbone and RetinaNet head

# General training
experiment_name: retina_unet_visceral 
device: cuda:7
val_interval: 1
debug_mode: False  # doesn't save checkpoints
seed: 10

epochs: 4000
lr: 2e-4
lr_backbone: 2e-5
weight_decay: 1e-4
clip_max_norm: -1 # Deactivated

# Scheduler
lr_drop: 2500

# Data
dataset: transoar_test_160160256_CT
overfit: False # use same set consisting of one image for train and val
bbox_padding: 1

# Dataloader
batch_size: 2
shuffle: True
num_workers: 8

# Model
backbone:
  # Encoder
  use_encoder_attn: False # Activates swin encoder

  # Standard params
  conv_kernels: [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]  # C0, C1, C2, C3, C4, C5
  strides: [[1, 1, 1], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]]
  in_channels: 1  #  Input channels 
  start_channels: 24  # Channels after first encoder block

  # Swin transformer params
  depths: [2, 2, 2, 2]
  num_heads: [3, 6, 12, 24]
  window_size: [7, 7, 7]
  mlp_ratio: 4
  qkv_bias: True
  qk_scale: null
  drop_rate: 0.
  attn_drop_rate: 0.
  drop_path_rate: 0.2
  conv_merging: False
  pre_merge: True

  # Decoder
  use_decoder_attn: False # Activated def attn
  
  # Standard params
  fpn_channels: 384 # Final output channels
  out_fmaps: [P2, P3, P4, P5]   # P0, P1, P2, P3, P4, P5

  # Def attn params
  pos_encoding: sine
  feature_levels: [P2, P3, P4, P5]
  hidden_dim: 192
  dim_feedforward: 512
  dropout: 0.1
  nheads: 6
  layers: 3
  n_points: 4
  use_cuda: False

  # Use segmentation proxy loss
  use_seg_proxy_loss: False

neck:
  # Input
  input_levels: [P2, P3, P4, P5]
  cls_reg_channels: 384
  seg_channels: 24

  # Heads
  head_channels: 192
  classifier_classes: 20
  loss_weight: 1.0  # for bce and giou
  prior_prob: 0.01 # for weight init of cls head
  learnabel_scale: True # for reg head

  # Matcher
  num_candidates: 4
  center_in_gt: False

  # Sampler
  batch_size_per_image: 32
  positive_fraction: 0.33
  pool_size: 20
  min_neg: 1

  # Post-processing
  detections_per_img: 100
  score_thresh: 0
  topk_candidates: 10000
  remove_small_boxes: 0.01
  nms_thresh: 0.6

  # Anchors
  anchors_per_position: 27
  stride: 1

  depth: [[6.0, 10.0, 32.0], [12.0, 20.0, 64.0], [24.0, 40.0, 128.0], [48.0, 80.0, 256.0]]  # TODO 512?
  height: [[8.0, 11.0, 16.0], [16.0, 22.0, 32.0], [32.0, 44.0, 64.0], [64.0, 88.0, 128.0]]
  width: [[6.0, 8.0, 11.0], [12.0, 16.0, 22.0], [24.0, 32.0, 44.0], [48.0, 64.0, 88.0]]

# Augmentation
augmentation:
  use_augmentation: True
  patch_size: [160, 160, 256]

  p_gaussian_noise: 0
  p_gaussian_smooth: 0
  p_intensity_scale: 0.5
  p_intensity_shift: 0.5
  p_adjust_contrast: 0
  p_rotate: 0.5
  p_zoom: 0.5
  p_shear: 0
  p_translate: 0.5
  p_flip: 0

  gaussian_noise_mean: 0.0
  gaussian_noise_std: 0.1
  gaussian_smooth_sigma: [0.5, 1.0]

  intensity_scale_factors: 0.1
  intensity_shift_offsets: 0.1

  adjust_contrast_gamma: [0.7, 1.5]

  rotation: [-15, 15]
  min_zoom: 0.8
  max_zoom: 1.2 
  translate_precentage: 10
  shear_range: [0.1, 0.1, 0.1]
  flip_axis: [0, 1, 2]