# Config file for light convnet + deformable detr combination

# General training
experiment_name: test_convnet_new_aug_crop_80_70_150
device: cuda:5
val_interval: 1
debug_mode: True  # doesn't save checkpoints
seed: 10

epochs: 500 # prev: 50
lr: 2e-4
lr_backbone: 2e-5
lr_linear_proj_mult: 0.1
weight_decay: 1e-4
clip_max_norm: 0.1

# Scheduler
lr_drop: 400  # prev: 40

# Data
dataset: transoar_test_CT
overfit: False # use same set consisting of one image for train and val
bbox_padding: 1

# Dataloader
batch_size: 2
shuffle: True
num_workers: 4

# Hungarian matching
set_cost_class: 2
set_cost_bbox: 5
set_cost_giou: 2

# Losses
loss_coefs:
  cls: 2
  bbox: 5
  giou: 2

# Model specific params
backbone:
  name: convnet_light
  num_channels: [64, 128, 256]
  kernel_size: [2, 2, 2]
  strides: [2, 2, 2]
  return_intermediate_outputs: True
  learnable: True

neck:
  name: def_detr
  skip_con: False # from backbone to heads
  pos_encoding: sine
  num_feature_levels: 3
  hidden_dim: 192 #832 # 192 # prev: 256
  dropout: 0.0 #0.1
  nheads: 6 #26 #6  #prev: 8
  dim_feedforward: 256 #1024
  enc_layers: 2 #6
  dec_layers: 2 #6
  enc_n_points: 4 #4
  dec_n_points: 4 #4
  num_queries: 20
  aux_loss: True
  use_cuda: True

# Augmentation
augmentation:
  use_augmentation: True
  patch_size: [80, 70, 150]

  p_gaussian_noise: 0.1 #0.1
  p_gaussian_smooth: 0.1 #0.2
  p_intensity_scale: 0.2 #0.15
  p_intensity_shift: 0.2
  p_adjust_contrast: 0.2 # 0.1, 0.3
  p_rotate: 0.5 #0.2
  p_zoom: 0.5 #0.2
  p_shear: 0.0
  p_axis_flip: 0.5 #0.5
  p_flip: 0.5 #0.5

  gaussian_noise_mean: 0.0
  gaussian_noise_std: 0.1
  gaussian_smooth_sigma: [0.5, 1.0]
  intensity_scale_factors: [0.75, 1.25]
  intensity_shift_offsets: [-0.1, 0.1]
  adjust_contrast_gamma: [0.7, 1.5]
  rotation: [-10, 10] #[-30, 30]
  min_zoom: 1.0 #0.7
  max_zoom: 1.2
  shear_range: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
  flip_axis: [0, 1, 2]