# Config file for data related params

# General
dataset_name: transoar_spacing_orig_th
modality: CT
path_to_gc_dataset: /home/bastian/datasets/visceral3/CT_GC
path_to_sc_dataset: /home/bastian/datasets/visceral3/CT_SC

# Dataset specific
num_classes: 20
labels:
  1: liver
  2: spleen
  3: pancreas,
  4: gall_bladder
  5: urinary_bladder
  6: aorta
  7: trachea
  8: right_lung
  9: left_lung
  10: sternum
  11: thyroid_gland
  12: first_lumbar_vertebra
  13: right_kidney
  14: left_kidney
  15: right_adrenal_gland
  16: left_adrenal_gland
  17: right_psoas_major
  18: left_psoas_major
  19: right_rectus_abdominis
  20: left_rectus_abdominis

# Preprocessing
fixed_size: True
foreground_normalization: True
target_spacing: False #[False, [x, x, x]]; if False: use estimated target spacing
bbox_padding: 1
cropping: True
key: image # [image, label]
margin: 2
orientation: RAS
min_num_organs: 12
anisotropy_threshold: 3
target_spacing_percentile: 50

# Augmentation
use_augmentation: True
p_rotation: 0.2
rotation: [-30, 30]
p_scale: 0.2
scale_range: [0.7, 1.4]
p_gamma: 0.3
gamma_range: [0.7, 1.5]
mirror_axes: [0, 1, 2]

# Dataloader
batch_size: 2
shuffle: False
num_workers: 0