# Config file for light convnet + deformable detr combination

# General training
experiment_name: test #anchor_matcher_0104tan_01offset_only_cdist
device: cuda:4
val_interval: 1
debug_mode: False  # doesn't save checkpoints
seed: 10

epochs: 500 # prev: 50
lr: 2e-4
lr_backbone: 2e-5
lr_linear_proj_mult: 0.1
weight_decay: 1e-4
clip_max_norm: 0.1

# Scheduler
lr_drop: 400  # prev: 40

# Data
dataset: transoar_testing_focused_attn_160_160_256_CT
overfit: False # use same set consisting of one image for train and val
bbox_padding: 1

# Dataloader
batch_size: 2
shuffle: True
num_workers: 4

# Matching
anchor_matching: True
set_cost_class: 0 #2
set_cost_bbox: 0 #5
set_cost_giou: 0 #2
set_cost_center: 1

# Losses
loss_coefs:
  cls: 2
  bbox: 5
  giou: 2

# Model specific params
backbone:
  name: fpn
  num_channels: 10
  start_filts: 18
  end_filts: 36
  res_architecture: resnet50
  n_channels: 1
  norm: null
  relu: relu
  n_latent_dims: 0
  operate_stride1: True
  sixth_pooling: False

neck:
  name: def_detr
  skip_con: False # from backbone to heads
  pos_encoding: sine
  num_feature_levels: 3
  hidden_dim: 192 #832 # prev: 256
  dropout: 0.1  # prev: 0.1
  nheads: 6 #26 #6  #prev: 8
  dim_feedforward: 256 # prev: 1024
  enc_layers: 2 #6
  dec_layers: 2 #6
  enc_n_points: 4 #4
  num_queries: 1620 #1620 #1200 #[20 * 20 * 3] #647 # [647 -> 3x3 cube]
  queries_per_organ: 27 #20
  anchor_offsets: 0.1
  input_shapes: [[21, 21, 33], [12, 12, 18], [6, 6, 9]]
  num_organs: 20
  aux_loss: True
  use_cuda: False

# Augmentation
augmentation:
  use_augmentation: True
  patch_size: [160, 160, 256] #null #[64, 64, 64]

  p_gaussian_noise: 0 #0.1
  p_gaussian_smooth: 0 #0.1
  p_intensity_scale: 0.5 #0.2
  p_intensity_shift: 0.5 #0.2
  p_adjust_contrast: 0 #0.2
  p_rotate: 0.5
  p_zoom: 0.5
  p_shear: 0.5
  p_translate: 0.5 # 0
  p_flip: 0 #0.5

  gaussian_noise_mean: 0.0
  gaussian_noise_std: 0.1
  gaussian_smooth_sigma: [0.5, 1.0]

  intensity_scale_factors: 0.1 #[0.75, 1.25]
  intensity_shift_offsets: 0.1

  adjust_contrast_gamma: [0.7, 1.5]

  rotation: [-15, 15]
  min_zoom: 0.8
  max_zoom: 1.2 
  translate_precentage: 10
  shear_range: [0.1, 0.1, 0.1]
  flip_axis: [0, 1, 2]