# Config file for parameters corresponding to exchangable parts of the model

backbones:
  swin_tiny:
    patch_size: [4,4,4]
    embed_dim: 96
    depths: [2, 2, 6, 2]
    num_heads: [3, 6, 12, 24]
    window_size: [8, 7, 7]
    mlp_ratio: 4.
    qkv_bias: True
    qk_scale: null
    drop_rate: 0.
    attn_drop_rate: 0.
    drop_path_rate: 0.2
    patch_norm: True

  senet:
    in_chans: 1
    depths: [4, 4, 8, 8]
    num_channels: 2048

necks:
  detr:
    hidden_dim: 256
    dropout: 0.1
    nheads: 8
    dim_feedforward: 2048
    enc_layers: 6
    dec_layers: 6
    pre_norm: False   # double check
    num_queries: 100
    aux_loss: True    # double ckeck
