# Config file for parameters corresponding to exchangable parts of the model

backbones:
  swin_tiny:
    patch_size: [4, 4, 4]
    embed_dim: 96
    depths: [2, 2, 6, 2]
    num_heads: [3, 6, 12, 24]
    window_size: [8, 7, 7]
    mlp_ratio: 4.
    qkv_bias: True
    qk_scale: null
    drop_rate: 0.
    attn_drop_rate: 0.
    drop_path_rate: 0.2
    patch_norm: True

  senet:
    in_chans: 1
    depths: [4, 4, 8, 8]
    strides: [1, 2, 2, 2] # prev. [1, 2, 2, 2]
    num_channels: 2048 # [64, 256, 512, 1024, 2048]
    feature_map_dim: [4, 4, 10]
    num_layers: 4 # [0, 1, 2, 3, 4]
    reduction: 16

necks:
  detr:
    skip_con: True # from backbone to heads
    pos_encoding: sine
    hidden_dim: 256 # TODO increase and test
    dropout: 0.1
    nheads: 8
    dim_feedforward: 2048
    enc_layers: 1 #6
    dec_layers: 1 #6
    pre_norm: False
    num_queries: 100 # spine-trans use 25
    aux_loss: False # TODO implement
