# Config file for preprocessing related params

# General
dataset_config: visceral
dataset_name: transoar_test_3mm
modality: CT
seed: 10
path_to_gc_dataset: /home/bastian/datasets/visceral3/CT_GC
path_to_sc_dataset: /home/bastian/datasets/visceral3/CT_SC

# Preprocessing
fixed_size: True
foreground_normalization: True
target_spacing: [3, 3, 3] #[False, [x, x, x]]; if False: use estimated target spacing
cropping: True
key: image # [image, label]
margin: 2
orientation: RAS
min_num_organs: 12