# Config file for resnet + deformable detr combination

# General training
experiment_name: 2mm_resnet_def_detr_noflip_lfirst3_q100_crop160_160_320_q100
device: cuda:5
val_interval: 1
debug_mode: True  # doesn't save checkpoints
seed: 10

epochs: 500 # prev: 50
lr: 2e-4
lr_backbone: 2e-5
lr_linear_proj_mult: 0.1
weight_decay: 1e-4
clip_max_norm: 0.1

# Scheduler
lr_drop: 400  # prev: 40

# Data
dataset: transoar_test_2mm_CT
overfit: False # use same set consisting of one image for train and val
bbox_padding: 1

# Dataloader
batch_size: 2
shuffle: True
num_workers: 8

# Hungarian matching
set_cost_class: 2
set_cost_bbox: 5
set_cost_giou: 2

# Losses
loss_coefs:
  cls: 2
  bbox: 5
  giou: 2

# Model specific params
backbone:
  name: resnet
  depths: [3, 4, 6, 3]
  strides: [1, 2, 2, 2]
  in_chans: 1
  num_channels: [192, 192, 192] #[512, 1024, 2048]
  num_feature_patches: 11040
  num_layers: 4
  pool: True
  return_intermediate_outputs: True

neck:
  name: def_detr
  skip_con: False # from backbone to heads
  pos_encoding: sine
  num_feature_levels: 3
  hidden_dim: 192 #832 # 192 # prev: 256
  dropout: 0.0
  nheads: 6 #26 #6  #prev: 8
  dim_feedforward: 1024
  enc_layers: 2 #6
  dec_layers: 2 #6
  enc_n_points: 4 #4
  dec_n_points: 4 #4
  num_queries: 100 #300
  aux_loss: True
  use_cuda: True

# Augmentation
augmentation:
  use_augmentation: True
  patch_size: [160, 160, 320] # div through 32#null #[64, 64, 64]

  p_gaussian_noise: 0.0 #0.1
  p_gaussian_smooth: 0.0 #0.1
  p_intensity_scale: 0.5 #0.2
  p_intensity_shift: 0.5 #0.2
  p_adjust_contrast: 0.0 #0.2
  p_rotate: 0.5
  p_zoom: 0.5
  p_shear: 0.5
  p_translate: 0.5
  p_flip: 0.0

  gaussian_noise_mean: 0.0
  gaussian_noise_std: 0.1
  gaussian_smooth_sigma: [0.5, 1.0]

  intensity_scale_factors: 0.1 #[0.75, 1.25]
  intensity_shift_offsets: 0.1

  adjust_contrast_gamma: [0.7, 1.5]

  rotation: [-15, 15]
  min_zoom: 0.8
  max_zoom: 1.2 
  translate_precentage: 10
  shear_range: [0.1, 0.1, 0.1]
  flip_axis: [0, 1, 2]
