# Config file for ResNet-DETR

# General training
experiment_name: test
device: cuda:4
val_interval: 1
debug_mode: True  # Doesn't save checkpoints
seed: 10

epochs: 2500
lr: 1e-4
lr_backbone: 1e-5
weight_decay: 1e-4
clip_max_norm: 0.1

# Scheduler
lr_drop: 2300

# Data
dataset: transoar_testing_focused_attn_160_160_256_CT
overfit: False # Use same set consisting of one image for train and val
bbox_padding: 1

# Dataloader
batch_size: 2
shuffle: True
num_workers: 4

# Hungarian matching
set_cost_class: 1
set_cost_bbox: 5
set_cost_giou: 2

# Losses
loss_coefs:
  cls: 2      # Detection
  bbox: 5
  giou: 2

# Model specific params
backbone:
  name: resnet
  depths: [3, 4, 6, 3]
  strides: [1, 2, 2, 2]
  in_chans: 1
  num_channels: 1024
  num_feature_patches: 160
  num_layers: 4
  pool: True
  return_intermediate_outputs: False

neck:
  name: detr
  
  pos_encoding: sine
  hidden_dim: 192
  dropout: 0.0  # prev: 0.1
  nheads: 6
  dim_feedforward: 1024 #2048
  enc_layers: 3 # prev: 6
  dec_layers: 3 # prev: 6
  pre_norm: False
  num_queries: 100
  aux_loss: True

# Augmentation
augmentation:
  use_augmentation: True
  patch_size: [160, 160, 256] #null #[64, 64, 64]

  p_gaussian_noise: 0 #0.1
  p_gaussian_smooth: 0 #0.1
  p_intensity_scale: 0.5 #0.2
  p_intensity_shift: 0.5 #0.2
  p_adjust_contrast: 0 #0.2
  p_rotate: 0.5
  p_zoom: 0.5
  p_shear: 0
  p_translate: 0.5
  p_flip: 0.5

  gaussian_noise_mean: 0.0
  gaussian_noise_std: 0.1
  gaussian_smooth_sigma: [0.5, 1.0]

  intensity_scale_factors: 0.1 #[0.75, 1.25]
  intensity_shift_offsets: 0.1

  adjust_contrast_gamma: [0.7, 1.5]

  rotation: [-15, 15]
  min_zoom: 0.8
  max_zoom: 1.2 
  translate_precentage: 10
  shear_range: [0.1, 0.1, 0.1]
  flip_axis: [0, 1, 2]
