# Config file for light convnet + deformable detr combination

# General training
experiment_name: test #test_orig_train_params_wh_160_flip_wd_switch
device: cuda:4
val_interval: 1
debug_mode: True  # doesn't save checkpoints
seed: 10

epochs: 1500 # prev: 50
lr: 2e-4
lr_backbone: 2e-5
lr_linear_proj_mult: 0.1
weight_decay: 1e-4
clip_max_norm: 0.1

# Scheduler
lr_drop: 400  # prev: 40

# Data
dataset: transoar_test_3mm_CT
overfit: False # use same set consisting of one image for train and val
bbox_padding: 1

# Dataloader
batch_size: 2
shuffle: True
num_workers: 4

# Hungarian matching
set_cost_class: 2
set_cost_bbox: 5
set_cost_giou: 2

# Losses
loss_coefs:
  cls: 2
  bbox: 5
  giou: 2

# Model specific params
model:
  # Encoder
  conv_kernels: [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]
  strides: [[1, 1, 1], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 1, 2]]
  in_channels: 1
  start_channels: 32
  max_channels: 320
  
  # Decoder
  decoder_levels: [2, 3, 4, 5, 6]
  fpn_channels: 128
  min_out_channels: 8
  upsampling_mode: transpose
  num_lateral: 1
  norm_lateral: False
  activation_lateral: False
  num_out: 1
  norm_out: False
  activation_out: False

  # Heads
  head_channels: 128
  classifier_classes: 20
  num_convs: 1
  norm_channels_per_group: 16
  norm_affine: True

  loss_weight: 1.0
  prior_prob: 0.01 # for weight init of cls head
  learnabel_scale: True # for reg head

  seg_classes: 20 # TODO we only do fgbg
  out_channels: [32, 64, 128, 128, 128, 128, 128]  # TODO make self config

  # check reductions
  # different weights for the losses, currently same

  # Sampler
  batch_size_per_image: 32
  positive_fraction: 0.33
  pool_size: 20
  min_neg: 1

  # Post-processing #General RetinaUnet
  detections_per_img: 100
  score_thresh: 0
  topk_candidates: 10000
  remove_small_boxes: 0.01
  nms_thresh: 0.6

  # Anchors
  anchors_per_position: 27
  stride: 1

  # 16bg facebook
  # width: [[5.0, 9.0, 15.0], [10.0, 18.0, 30.0], [20.0, 36.0, 60.0], [40.0, 72.0, 120.0], [80.0, 144.0, 240.0]]
  # height: [[5.0, 7.0, 13.0], [10.0, 14.0, 26.0], [20.0, 28.0, 52.0], [40.0, 56.0, 104.0], [40.0, 56.0, 104.0]]
  # depth: [[4.0, 6.0, 17.0], [8.0, 12.0, 34.0], [16.0, 24.0, 68.0], [32.0, 48.0, 136.0], [32.0, 48.0, 136.0]]

  # 48bg giga 160 160 256
  depth: [[6.0, 9.0, 22.0], [12.0, 18.0, 44.0], [24.0, 36.0, 88.0], [48.0, 72.0, 176.0], [96.0, 144.0, 352.0]]
  height: [[6.0, 9.0, 14.0], [12.0, 18.0, 28.0], [24.0, 36.0, 56.0], [48.0, 72.0, 112.0], [48.0, 72.0, 112.0]]  # TODO last scale not done
  width: [[5.0, 7.0, 11.0], [10.0, 14.0, 22.0], [20.0, 28.0, 44.0], [40.0, 56.0, 88.0], [40.0, 56.0, 88.0]]

  # Matcher
  num_candidates: 4
  center_in_gt: False
  

# Augmentation
augmentation:
  use_augmentation: True
  patch_size: [160, 160, 256] #null #[64, 64, 64]

  p_gaussian_noise: 0 #0.1
  p_gaussian_smooth: 0 #0.1
  p_intensity_scale: 0.5 #0.2
  p_intensity_shift: 0.5 #0.2
  p_adjust_contrast: 0 #0.2
  p_rotate: 0.5
  p_zoom: 0.5
  p_shear: 0.5
  p_translate: 0.5 # 0
  p_flip: 0.5

  gaussian_noise_mean: 0.0
  gaussian_noise_std: 0.1
  gaussian_smooth_sigma: [0.5, 1.0]

  intensity_scale_factors: 0.1 #[0.75, 1.25]
  intensity_shift_offsets: 0.1

  adjust_contrast_gamma: [0.7, 1.5]

  rotation: [-15, 15]
  min_zoom: 0.8
  max_zoom: 1.2 
  translate_precentage: 10
  shear_range: [0.1, 0.1, 0.1]
  flip_axis: [0, 1, 2]