# Config file for senet + detr combination

# General training
experiment_name: test #senet_detr_22_q100_h257_shuffle #test_aux_loss #senet_kernel3_noworkerinit_prevseed_repr
device: cuda:5
val_interval: 1
debug_mode: True  # doesn't save checkpoints
seed: 10

epochs: 2000 #3300 # should be about ~300k train steps, prev
lr: 1e-4  # spine 1e-5
lr_backbone: 1e-5 # spine-trans: 1e-6
weight_decay: 1e-4
clip_max_norm: 0.1

# Scheduler
lr_drop: 1300 #2700 # at about 2/3 of train run

# Data
dataset: transoar_spacing444_th_newconf_CT
overfit: False # use same set consisting of one image for train and val
bbox_padding: 1

# Augmentation
use_augmentation: True
p_rotation: 0.2 # prev: 0.2
rotation: [-30, 30]
p_scale: 0.2 # prev: 0.2
scale_range: [0.7, 1.4]
p_gamma: 0.3
gamma_range: [0.7, 1.5]
mirror_axes: [0, 1, 2]

# Dataloader
batch_size: 3
shuffle: True  # TODO
num_workers: 4

# Hungarian matching
set_cost_class: 1
set_cost_bbox: 5
set_cost_giou: 2

# Losses
loss_coefs:
  cls: 1
  bbox: 5
  giou: 2

# Model specific params
backbone:
  name: senet
  in_chans: 1
  depths: [4, 4, 8, 8]
  strides: [1, 2, 2, 2] # prev. [1, 2, 2, 2]
  num_channels: 2048 # [64, 256, 512, 1024, 2048]
  num_feature_patches: 160
  num_layers: 4 # [0, 1, 2, 3, 4]
  reduction: 16
  pool: True
  return_intermediate_outputs: False

neck:
  name: detr
  skip_con: False # from backbone to heads
  pos_encoding: sine
  hidden_dim: 256 # prev: 256 -> 768
  dropout: 0  # prev: 0.1
  nheads: 8
  dim_feedforward: 2048
  enc_layers: 2 #6
  dec_layers: 2 #6
  pre_norm: False
  num_queries: 100 # spine-trans: 25
  aux_loss: False