# Config file for senet + deformable detr combination

# General training
experiment_name: test #_def #senet_def_detr
device: cuda:7
val_interval: 1
debug_mode: True  # doesn't save checkpoints
seed: 10

epochs: 500 # prev: 50
lr: 2e-4
lr_backbone: 2e-5
lr_linear_proj_mult: 0.1
weight_decay: 1e-4
clip_max_norm: 0.1

# Scheduler
lr_drop: 400  # prev: 40

# Data
dataset: transoar_spacing444_th_newconf_CT
overfit: False # use same set consisting of one image for train and val
bbox_padding: 1

# Augmentation
use_augmentation: True
p_rotation: 0.2
rotation: [-30, 30]
p_scale: 0.2
scale_range: [0.7, 1.4]
p_gamma: 0.3
gamma_range: [0.7, 1.5]
mirror_axes: [0, 1, 2]

# Dataloader
batch_size: 1
shuffle: False  # TODO
num_workers: 4

# Hungarian matching
set_cost_class: 2
set_cost_bbox: 5
set_cost_giou: 2

# Losses
loss_coefs:
  cls: 2
  bbox: 5
  giou: 2
  focal_alpha: 0.25

# Model specific params
backbone:
  name: senet
  in_chans: 1
  depths: [4, 4, 8, 8]
  strides: [1, 2, 2, 2] # prev. [1, 2, 2, 2]
  num_channels: [512, 1024, 2048] #[64, 256, 512, 1024, 2048]
  feature_map_dim: [4, 4, 10]
  num_layers: 4 # [0, 1, 2, 3, 4]
  reduction: 16
  pool: True
  return_intermediate_outputs: True

neck:
  name: def_detr
  skip_con: False # from backbone to heads TODO
  pos_encoding: sine
  pos_encoding_scale: 6.28318530718 # 2 * np.pi2
  num_feature_levels: 3
  hidden_dim: 192 #832 # prev: 256
  dropout: 0.1
  nheads: 6 #26  #prev: 8
  dim_feedforward: 1024
  enc_layers: 1 #6
  dec_layers: 1 #6
  enc_n_points: 4
  dec_n_points: 4
  num_queries: 300
  aux_loss: True

  two_stage: False  # TODO
  box_refine: False # TODO
