# Config file for params related to training

# General training
experiment_name: test
device: cuda:0
val_interval: 1

epochs: 300
lr: 1e-4
lr_backbone: 1e-5
weight_decay: 1e-4
clip_max_norm: 0.1

# Scheduler
lr_drop: 200

# Hungarian matching
set_cost_class: 1
set_cost_bbox: 5
set_cost_giou: 4

# Losses
eos_coef: 0.1
loss_coefs:
  cls_loss_coef: 1
  bbox_loss_coef: 5
  giou_loss_coef: 2