# Config file for params related to training

# General training
experiment_name: test #test_bbstrides1222_layer22_q50_b3_h768_nodrop_noskip_realval
device: cuda:3
val_interval: 1
debug_mode: False  # doesn't save checkpoints
seed: 10

epochs: 1500 # should be about ~300k train steps, prev: 300
lr: 1e-4
lr_backbone: 1e-5
weight_decay: 1e-4
clip_max_norm: 0.1

# Scheduler
lr_drop: 1200 #prev: 200

# Hungarian matching
set_cost_class: 1
set_cost_bbox: 5
set_cost_giou: 4

# Losses
eos_coef: 0.1
loss_coefs:
  cls: 1
  bbox: 5
  giou: 2