# Config file of visceral multi-organ dataset

num_classes: 20
labels:
  1: liver
  2: spleen
  3: pancreas
  4: gall_bladder
  5: urinary_bladder
  6: aorta
  7: trachea
  8: right_lung
  9: left_lung
  10: sternum
  11: thyroid_gland
  12: first_lumbar_vertebra
  13: right_kidney
  14: left_kidney
  15: right_adrenal_gland
  16: left_adrenal_gland
  17: right_psoas_major
  18: left_psoas_major
  19: right_rectus_abdominis
  20: left_rectus_abdominis

labels_small:
  3: pancreas
  4: gall_bladder
  5: urinary_bladder
  7: trachea
  11: thyroid_gland
  12: first_lumbar_vertebra
  15: right_adrenal_gland
  16: left_adrenal_gland

labels_mid:
  2: spleen
  6: aorta
  10: sternum
  13: right_kidney
  14: left_kidney
  17: right_psoas_major
  18: left_psoas_major
  19: right_rectus_abdominis
  20: left_rectus_abdominis

labels_large:
  1: liver
  8: right_lung
  9: left_lung
